import { createContext, useContext } from "react";

export type Language = "es" | "en";

export interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

export const translations: Translations = {
  es: {
    loginTitle: "Bienvenido de nuevo",
    loginSubtitle: "Inicia sesión para acceder a tu cuenta",
    email: "Correo Electrónico",
    password: "Contraseña",
    rememberMe: "Recordarme",
    forgotPassword: "¿Olvidaste tu contraseña?",
    loginButton: "Iniciar Sesión",
    loggingIn: "Iniciando...",
    noAccount: "¿No tienes una cuenta?",
    register: "Regístrate aquí",
    errorLogin: "Credenciales incorrectas",
    serverError: "Error del servidor",
    language: "Idioma",
    brandingHeadline: "Gestiona tu equipo con confianza.",
    brandingSubheadline: "La plataforma integral para administrar usuarios, estudios y direcciones en un solo lugar.",
    featureSecurity: "Autenticación segura con JWT",
    featureSpeed: "Panel de control en tiempo real",
    featureExperience: "Diseñado para equipos modernos",
    navDashboard: "Dashboard",
    navUsers: "Usuarios",
    navProfile: "Mi Perfil",
    navStudies: "Estudios",
    navAddresses: "Direcciones",
    roleAdmin: "Administrador",
    roleUser: "Usuario",
    navAdminStudies: "Estudios (Global)",
    navAdminAddresses: "Direcciones (Global)",
    logout: "Cerrar Sesión",
    logoutShort: "Salir",
    panel: "Panel",
    welcome: "¡Hola de nuevo!",
    dashboardSubtitle: "Aquí tienes un resumen de tu actividad.",
    totalUsers: "Usuarios Totales",
    activeStudies: "Estudios Activos",
    savedAddresses: "Direcciones Guardadas",
    viewAll: "Ver todo",
    quickActions: "Acciones Rápidas",
    editProfile: "Editar Perfil",
    addStudy: "Añadir Estudio",
    addAddress: "Añadir Dirección",
    settings: "Configuración",
    noUsersFound: "No se encontraron usuarios.",
    personalData: "Datos Personales",
    institution: "Institución",
    startDate: "Fecha Inicio",
    endDate: "Fecha Fin",
    description: "Descripción",
    street: "Calle",
    city: "Ciudad",
    state: "Provincia/Estado",
    zipCode: "Código Postal",
    country: "País",
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Eliminar",
    add: "Agregar",
    successAdd: "Agregado con éxito",
    successUpdate: "Actualizado con éxito",
    successDelete: "Eliminado con éxito",
    profileTitle: "Configuración de Perfil",
    profileSubtitle: "Administra tu información personal, académica y de ubicación.",
    // --- User management ---
    name: "Nombre",
    lastName: "Apellido",
    firstName: "Nombre",
    role: "Rol",
    actions: "Acciones",
    searchUsers: "Buscar usuarios...",
    deleteConfirm: "¿Estás seguro de eliminar a este usuario?",
    userStatus: "Estado",
    lastLogin: "Último acceso",
    manageUsersTitle: "Gestión de Usuarios",
    manageUsersSubtitle: "Administra las cuentas y roles de tu organización.",
    systemStatus: "Estado del Sistema",
    online: "En Línea",
    vsLastMonth: "vs mes anterior",
    academicRecords: "Registros Académicos",
    noStudiesYet: "Aún no hay estudios cargados",
    noAddressesYet: "Aún no hay direcciones cargadas",
    personalAddresses: "Direcciones Personales",
    addressRecords: "Registros de Ubicación",
    manageStudiesTitle: "Gestión Global de Estudios",
    manageStudiesSubtitle: "Administra todos los registros académicos del sistema.",
    manageAddressesTitle: "Gestión Global de Direcciones",
    manageAddressesSubtitle: "Administra todas las ubicaciones registradas en el sistema.",
    includeInactive: "Ver Inactivos",
    page: "Página",
    noStudiesFound: "No se encontraron estudios.",
    noAddressesFound: "No se encontraron direcciones.",
    user: "Usuario",
    active: "Activo",
    account: "Cuenta",
  },
  en: {
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to access your account",
    email: "Email Address",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    loginButton: "Sign In",
    loggingIn: "Signing in...",
    noAccount: "Don't have an account?",
    register: "Register here",
    errorLogin: "Incorrect credentials",
    serverError: "Server error",
    language: "Language",
    brandingHeadline: "Manage your team with confidence.",
    brandingSubheadline: "The all-in-one platform to manage users, studies and addresses in one place.",
    featureSecurity: "Secure JWT authentication",
    featureSpeed: "Real-time control panel",
    featureExperience: "Built for modern teams",
    navDashboard: "Dashboard",
    navUsers: "Users",
    navProfile: "Profile",
    navStudies: "Studies",
    navAddresses: "Addresses",
    roleAdmin: "Administrator",
    roleUser: "User",
    navAdminStudies: "Studies (Global)",
    navAdminAddresses: "Addresses (Global)",
    logout: "Log Out",
    logoutShort: "Quit",
    panel: "Panel",
    welcome: "Hello again!",
    dashboardSubtitle: "Here is a summary of your activity.",
    totalUsers: "Total Users",
    activeStudies: "Active Studies",
    savedAddresses: "Saved Addresses",
    viewAll: "View all",
    quickActions: "Quick Actions",
    editProfile: "Edit Profile",
    addStudy: "Add Study",
    addAddress: "Add Address",
    settings: "Settings",
    name: "First Name",
    lastName: "Last Name",
    role: "Role",
    actions: "Actions",
    searchUsers: "Search users...",
    deleteConfirm: "Are you sure you want to delete this user?",
    userStatus: "Status",
    lastLogin: "Last Login",
    noUsersFound: "No users found.",
    personalData: "Personal Information",
    institution: "Institution",
    startDate: "Start Date",
    endDate: "End Date",
    description: "Description",
    street: "Street",
    city: "City",
    state: "State/Province",
    zipCode: "Zip Code",
    country: "Country",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    successAdd: "Added successfully",
    successUpdate: "Updated successfully",
    successDelete: "Deleted successfully",
    profileTitle: "Profile Settings",
    profileSubtitle: "Manage your personal information, academic background, and locations.",
    // --- User management ---
    firstName: "First Name",
    manageUsersTitle: "User Management",
    manageUsersSubtitle: "Manage your organization's user accounts and roles.",
    systemStatus: "System Status",
    online: "Online",
    vsLastMonth: "vs last month",
    academicRecords: "Academic Records",
    noStudiesYet: "No studies added yet",
    noAddressesYet: "No addresses added yet",
    personalAddresses: "Personal Addresses",
    addressRecords: "Location Records",
    manageStudiesTitle: "Global Study Management",
    manageStudiesSubtitle: "Manage all academic records in the system.",
    manageAddressesTitle: "Global Address Management",
    manageAddressesSubtitle: "Manage all registered locations in the system.",
    includeInactive: "Show Inactive",
    page: "Page",
    noStudiesFound: "No studies found.",
    noAddressesFound: "No addresses found.",
    user: "User",
    active: "Active",
    account: "Account",
  },
};

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
